name: Python CI # Just workflow name

# To trigger the workflow we need events to be mentioned.
# Trigger the workflow on any push to the main 

on: # on works like -- "trigger on"
  push:
    branches:
      - main  # trigger on every push in to main branch
  pull_request:
    branches:
      -main  # trigger on every pull request from main branch


jobs: # jobs means the things has to be done while triggered something:
  test:
    runs-on: ubuntu-latest # we run test cases on ubuntu-latest containers provided by github 

    steps: # actions to be done
      # step 1:
      - name: Check out code
        uses: actions/checkout@v2 # prebuilt github action to

      # step 2
      - name: Set up python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.8"

      # step 3:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
        
      



